### ISSUE TITLE
Doesn't work without explicit annotations?

### ISSUE THREAD

**Issue by mrjones2014** [calops/hmts.nvim#9] opened 2023-08-22 13:23 UTC
In the injections file (https://github.com/calops/hmts.nvim/blob/main/queries/nix/injections.scm) I see that `programs.fish.shellInit`, `programs.fish.function` etc. are specified, but they still don't work for me without explicit annotations:

| Plugin installed, but no annotations | with explicit annotations |
| -- | -- |
|  ![image](https://github.com/calops/hmts.nvim/assets/8648891/f118c8ba-f178-489d-9e16-25cf28662a85) |  ![image](https://github.com/calops/hmts.nvim/assets/8648891/f8e91cc7-7a40-4c46-8d5a-f91241c3d670) |

**Comment by mrjones2014** [comment] 2023-08-22 13:24
I see that the injections file doesn't go down into `body` for functions, but I have some there that are raw strings and it still doesn't work for those.

**Comment by mrjones2014** [comment] 2023-08-22 13:28
It also doesn't work if the shebang line in a script is something like `!#${pkgs.bash}/bin/bash`.

Awesome plugin if I can get these working though!

**Comment by mrjones2014** [comment] 2023-08-22 16:47
Neovim version if that's relevant, maybe something broke on nightly:

```
NVIM v0.10.0-dev-3f1a12b
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

**Comment by calops** [comment] 2023-08-22 18:09
Thanks for all these reports! I'll look into it shortly

**Comment by calops** [comment] 2023-08-22 22:27
#10 should fix the first issues you mentioned.

However, the `!#${pkgs.bash}/bin/bash` thing is going to be tricker to implement, because it makes the shebang span multiple nodes instead of just one `string_fragment`. Perhaps not impossible, but it'll take some thinking.

In the meantime, I recommend using explicit annotations for these cases.

**Comment by calops** [comment] 2023-08-22 22:29
Oh, and another thing: I hadn't accounted for the possibility to have functions written as anything else than plain strings (in your example there's a `body` and `description`. I'll draft a PR to support this.

**Comment by calops** [comment] 2023-08-22 22:40
There you go. I will close this issue and open a new one about the shebang thing.

**Closed by calops** 2023-08-22 22:40 UTC
Labels: bug

**Comment by mrjones2014** [comment] 2023-08-23 02:32
Amazing thanks!

**Comment by mrjones2014** [comment] 2023-08-23 10:46
Hmm, @calops #10 seems to only partly work for me. I am not sure why, but it works for my [home-manager/modules/fish.nix](https://github.com/mrjones2014/dotfiles/blob/b89131c54e24c068aa4a5e520de8391ff346b713/home-manager/modules/fish.nix) but not the fish functions in my [home-manager/modules/fzf.nix](https://github.com/mrjones2014/dotfiles/blob/b89131c54e24c068aa4a5e520de8391ff346b713/home-manager/modules/fzf.nix)

**Comment by mrjones2014** [comment] 2023-08-23 16:10
Only difference I can see between the files is the way the properties are nested, but I tried nesting it the same way and it doesn't fix the issue :/

**Comment by calops** [comment] 2023-08-25 12:24
Indeed I can reproduce this bug. Could you open a new issue about this? Thanks!

**Comment by calops** [comment] 2023-08-25 12:27
However the nesting seems to be the issue from the tests I've made. Could you show me a file where it's nested like the first but still doesn't work?

**Comment by mrjones2014** [comment] 2023-08-25 12:37
I'll open a new issue with some examples in a few minutes 👍

**Comment by mrjones2014** [comment] 2023-08-25 12:39
As of today it actually does seem to work if I match the nesting, however I'll still open an issue about the nesting.
